os:   linux
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - sudo apt install ninja-build

script:
  - git submodule update --init
  - ./scripts/patch.sh
  - cd qemu
  - ./configure --target-list=riscv64-softmmu,riscv32-softmmu --extra-ldflags=-lrt
  - make -j
